#
# alone : application framework for embedded systems.
#   Copyright (c) 2010 FAR END Technologies Corporation.
#   Copyright (c) 2025- Hirohito Higashi All Rights Reserved.
#
# This file is destributed under BSD License. Please read the LICENSE file.
#

require 'rbconfig'

RUBYPATH = File.join(RbConfig::CONFIG['bindir'], RbConfig::CONFIG['ruby_install_name']) + RbConfig::CONFIG['EXEEXT']
AL_CONF_DIR = File.expand_path( File.dirname(__FILE__) + "/../alone" )

$LOAD_PATH << AL_CONF_DIR


task :default => [] do
  sh "rake -T", verbose:false
end


########################################
# About AlGraph
########################################

desc "Testing the Graph module"
task :graph do
  Dir.glob("graph/test_*.rb").each {|test|
    require_relative test
  }
end


########################################
# About database
# (接続情報の保存機能テストのため、ファイルを一つずつテスト)
########################################

##
# RDB wrapper 複数使用のテストをすべて実行する。
#
desc "Testing the RDB wrapper combination test"
task :rdbw_combination do
  Dir.glob("rdbw/combination/test_*.rb").each {|test|
    exit if system( RUBYPATH, "-I#{AL_CONF_DIR}", test ) == false
  }
end

##
# PostgreSQL 関連のテストをすべて実行する。
#
desc "Testing the RDB wrapper (PostgreSQL based)"
task :rdbw_postgres do
  Dir.glob("rdbw/postgres/test_*.rb").each {|test|
    exit if system( RUBYPATH, "-I#{AL_CONF_DIR}", test ) == false
  }
end

##
# Mysql2 関連のテストをすべて実行する。
#
desc "Testing the RDB wrapper (MySQL based)"
task :rdbw_mysql do
  Dir.glob("rdbw/mysql2/test_*.rb").each {|test|
    exit if system( RUBYPATH, "-I#{AL_CONF_DIR}", test ) == false
  }
end

##
# SQLite 関連のテストをすべて実行する。
#
desc "Testing the RDB wrapper (SQLite based)"
task :rdbw_sqlite do
  Dir.glob("rdbw/sqlite/test_*.rb").each {|test|
    exit if system( RUBYPATH, "-I#{AL_CONF_DIR}", test ) == false
  }
end


########################################
# About AlPersist
########################################

##
# for AlPersist::Sqlite
#
desc "Testing the DataPersist module (SQLite-based)"
task :persist_sqlite do
  require_relative "persist/test_sqlite.rb"
end
